// Imagino que luego pasaremos esto a un JSON
// Generé un .csv desde un artículo y luego lo convertí online a objeto 

export const verbos = [
    {
        "popularityRank": 1,
        "infinitive": "to be",
        "infinitiveExtraInfo": "I, he, she it",
        "simplePast": "was",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "been",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 2,
        "infinitive": "to be",
        "infinitiveExtraInfo": "you, we, they",
        "simplePast": "were",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "been",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 3,
        "infinitive": "to have",
        "infinitiveExtraInfo": "",
        "simplePast": "had",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "had",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 4,
        "infinitive": "to do",
        "infinitiveExtraInfo": "",
        "simplePast": "did",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "done",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 5,
        "infinitive": "to say",
        "infinitiveExtraInfo": "",
        "simplePast": "said",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "said",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 6,
        "infinitive": "to go",
        "infinitiveExtraInfo": "",
        "simplePast": "went",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "gone",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 7,
        "infinitive": "to get",
        "infinitiveExtraInfo": "",
        "simplePast": "got",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "got",
        "pastParticipleAlt": "gotten",
        "pastParticipleExtraInfo": "in US English, \"gotten\" is similar to \"obtain\" and \"got\" is more like \"have",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 8,
        "infinitive": "to make",
        "infinitiveExtraInfo": "",
        "simplePast": "made",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "made",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 9,
        "infinitive": "to know",
        "infinitiveExtraInfo": "",
        "simplePast": "knew",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "known",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 10,
        "infinitive": "to think",
        "infinitiveExtraInfo": "",
        "simplePast": "thought",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "thought",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 11,
        "infinitive": "to take",
        "infinitiveExtraInfo": "",
        "simplePast": "took",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "taken",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 12,
        "infinitive": "to see",
        "infinitiveExtraInfo": "",
        "simplePast": "saw",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "seen",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 13,
        "infinitive": "to come",
        "infinitiveExtraInfo": "",
        "simplePast": "came",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "come",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 14,
        "infinitive": "to find",
        "infinitiveExtraInfo": "",
        "simplePast": "found",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "found",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 15,
        "infinitive": "to give",
        "infinitiveExtraInfo": "",
        "simplePast": "gave",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "given",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 16,
        "infinitive": "to tell",
        "infinitiveExtraInfo": "",
        "simplePast": "told",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "told",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 17,
        "infinitive": "to feel",
        "infinitiveExtraInfo": "",
        "simplePast": "felt",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "felt",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 18,
        "infinitive": "to become",
        "infinitiveExtraInfo": "",
        "simplePast": "became",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "become",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 19,
        "infinitive": "to leave",
        "infinitiveExtraInfo": "",
        "simplePast": "left",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "left",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 20,
        "infinitive": "to put",
        "infinitiveExtraInfo": "",
        "simplePast": "put",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "put",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 21,
        "infinitive": "to mean",
        "infinitiveExtraInfo": "",
        "simplePast": "meant",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "meant",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 22,
        "infinitive": "to keep",
        "infinitiveExtraInfo": "",
        "simplePast": "kept",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "kept",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 23,
        "infinitive": "to let",
        "infinitiveExtraInfo": "",
        "simplePast": "let",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "let",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 24,
        "infinitive": "to begin",
        "infinitiveExtraInfo": "",
        "simplePast": "began",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "begun",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 25,
        "infinitive": "to show",
        "infinitiveExtraInfo": "",
        "simplePast": "showed",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "shown",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 26,
        "infinitive": "to hear",
        "infinitiveExtraInfo": "",
        "simplePast": "heard",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "heard",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 27,
        "infinitive": "to run",
        "infinitiveExtraInfo": "",
        "simplePast": "ran",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "run",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 28,
        "infinitive": "to hold",
        "infinitiveExtraInfo": "",
        "simplePast": "held",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "held",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 29,
        "infinitive": "to bring",
        "infinitiveExtraInfo": "",
        "simplePast": "brought",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "brought",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 30,
        "infinitive": "to write",
        "infinitiveExtraInfo": "",
        "simplePast": "wrote",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "written",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 31,
        "infinitive": "to sit",
        "infinitiveExtraInfo": "",
        "simplePast": "sat",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "sat",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 32,
        "infinitive": "to stand",
        "infinitiveExtraInfo": "",
        "simplePast": "stood",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "stood",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 33,
        "infinitive": "to lose",
        "infinitiveExtraInfo": "",
        "simplePast": "lost",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "lost",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 34,
        "infinitive": "to pay",
        "infinitiveExtraInfo": "",
        "simplePast": "paid",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "paid",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 35,
        "infinitive": "to meet",
        "infinitiveExtraInfo": "",
        "simplePast": "met",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "met",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 36,
        "infinitive": "to set",
        "infinitiveExtraInfo": "",
        "simplePast": "set",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "set",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 37,
        "infinitive": "to learn",
        "infinitiveExtraInfo": "",
        "simplePast": "learnt",
        "simplePastAlt": "learned",
        "simplePastExtraInfo": "both forms are correct",
        "pastParticiple": "learnt",
        "pastParticipleAlt": "learned",
        "pastParticipleExtraInfo": "both forms are correct",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 38,
        "infinitive": "to lead",
        "infinitiveExtraInfo": "",
        "simplePast": "led",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "led",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 39,
        "infinitive": "to understand",
        "infinitiveExtraInfo": "",
        "simplePast": "understood",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "understood",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 40,
        "infinitive": "to speak",
        "infinitiveExtraInfo": "",
        "simplePast": "spoke",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "spoken",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 41,
        "infinitive": "to read",
        "infinitiveExtraInfo": "",
        "simplePast": "read",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "read",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 42,
        "infinitive": "to spend",
        "infinitiveExtraInfo": "",
        "simplePast": "spent",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "spent",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 43,
        "infinitive": "to grow",
        "infinitiveExtraInfo": "",
        "simplePast": "grew",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "grown",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 44,
        "infinitive": "to win",
        "infinitiveExtraInfo": "",
        "simplePast": "won",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "won",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 45,
        "infinitive": "to buy",
        "infinitiveExtraInfo": "",
        "simplePast": "bought",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "bought",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 46,
        "infinitive": "to send",
        "infinitiveExtraInfo": "",
        "simplePast": "sent",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "sent",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 47,
        "infinitive": "to build",
        "infinitiveExtraInfo": "",
        "simplePast": "built",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "built",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 48,
        "infinitive": "to fall",
        "infinitiveExtraInfo": "",
        "simplePast": "fell",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "fallen",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 49,
        "infinitive": "to cut",
        "infinitiveExtraInfo": "",
        "simplePast": "cut",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "cut",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 50,
        "infinitive": "to sell",
        "infinitiveExtraInfo": "",
        "simplePast": "sold",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "sold",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 51,
        "infinitive": "to drive",
        "infinitiveExtraInfo": "",
        "simplePast": "drove",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "driven",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 52,
        "infinitive": "to break",
        "infinitiveExtraInfo": "",
        "simplePast": "broke",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "broken",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 53,
        "infinitive": "to wear",
        "infinitiveExtraInfo": "",
        "simplePast": "wore",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "worn",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 54,
        "infinitive": "to hit",
        "infinitiveExtraInfo": "",
        "simplePast": "hit",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "hit",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 55,
        "infinitive": "to eat",
        "infinitiveExtraInfo": "",
        "simplePast": "ate",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "eaten",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 56,
        "infinitive": "to teach",
        "infinitiveExtraInfo": "",
        "simplePast": "taught",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "taught",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 57,
        "infinitive": "to catch",
        "infinitiveExtraInfo": "",
        "simplePast": "caught",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "caught",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 58,
        "infinitive": "to draw",
        "infinitiveExtraInfo": "",
        "simplePast": "drew",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "drawn",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 59,
        "infinitive": "to choose",
        "infinitiveExtraInfo": "",
        "simplePast": "chose",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "chosen",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 60,
        "infinitive": "to seek",
        "infinitiveExtraInfo": "",
        "simplePast": "sought",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "sought",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 61,
        "infinitive": "to deal",
        "infinitiveExtraInfo": "",
        "simplePast": "dealt",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "dealt",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 62,
        "infinitive": "to fight",
        "infinitiveExtraInfo": "",
        "simplePast": "fought",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "fought",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 63,
        "infinitive": "to throw",
        "infinitiveExtraInfo": "",
        "simplePast": "threw",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "thrown",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 64,
        "infinitive": "to rise",
        "infinitiveExtraInfo": "",
        "simplePast": "rose",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "risen",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 65,
        "infinitive": "to shoot",
        "infinitiveExtraInfo": "",
        "simplePast": "shot",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "shot",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 66,
        "infinitive": "to lie",
        "infinitiveExtraInfo": "to be in a horizontal position",
        "simplePast": "lay",
        "simplePastAlt": "",
        "simplePastExtraInfo": "other definitions are not irregular",
        "pastParticiple": "lain",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "other definitions are not irregular",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 67,
        "infinitive": "to lie",
        "infinitiveExtraInfo": "to say false things",
        "simplePast": "lied",
        "simplePastAlt": "",
        "simplePastExtraInfo": "this definition of this verb is regular",
        "pastParticiple": "lied",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "this definition of this verb is regular",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 68,
        "infinitive": "to prove",
        "infinitiveExtraInfo": "",
        "simplePast": "proved",
        "simplePastAlt": "",
        "simplePastExtraInfo": "the simple past is regular",
        "pastParticiple": "proved",
        "pastParticipleAlt": "proven",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 69,
        "infinitive": "to hang",
        "infinitiveExtraInfo": "to attach or suspend",
        "simplePast": "hung",
        "simplePastAlt": "",
        "simplePastExtraInfo": "other definitions are not irregular",
        "pastParticiple": "hung",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "other definitions are not irregular",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 70,
        "infinitive": "to hang",
        "infinitiveExtraInfo": "to suspend by the neck until dead",
        "simplePast": "hanged",
        "simplePastAlt": "",
        "simplePastExtraInfo": "this definition of this verb is regular",
        "pastParticiple": "hanged",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "this definition of this verb is regular",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 71,
        "infinitive": "to forget",
        "infinitiveExtraInfo": "",
        "simplePast": "forgot",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "forgotten",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 72,
        "infinitive": "to shake",
        "infinitiveExtraInfo": "",
        "simplePast": "shook",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "shaken",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 73,
        "infinitive": "to fly",
        "infinitiveExtraInfo": "",
        "simplePast": "flew",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "flown",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 74,
        "infinitive": "to sing",
        "infinitiveExtraInfo": "",
        "simplePast": "sang",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "sung",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 75,
        "infinitive": "to beat",
        "infinitiveExtraInfo": "",
        "simplePast": "beat",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "beaten",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 76,
        "infinitive": "to cost",
        "infinitiveExtraInfo": "",
        "simplePast": "cost",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "cost",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 77,
        "infinitive": "to hurt",
        "infinitiveExtraInfo": "",
        "simplePast": "hurt",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "hurt",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 78,
        "infinitive": "to strike",
        "infinitiveExtraInfo": "",
        "simplePast": "struck",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "struck",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 79,
        "infinitive": "to sleep",
        "infinitiveExtraInfo": "",
        "simplePast": "slept",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "slept",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 80,
        "infinitive": "to stick",
        "infinitiveExtraInfo": "",
        "simplePast": "stuck",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "stuck",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 81,
        "infinitive": "to drink",
        "infinitiveExtraInfo": "",
        "simplePast": "drank",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "drunk",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 82,
        "infinitive": "to hide",
        "infinitiveExtraInfo": "",
        "simplePast": "hid",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "hidden",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 83,
        "infinitive": "to ride",
        "infinitiveExtraInfo": "",
        "simplePast": "rode",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "ridden",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 84,
        "infinitive": "to feed",
        "infinitiveExtraInfo": "",
        "simplePast": "fed",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "fed",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 85,
        "infinitive": "to spread",
        "infinitiveExtraInfo": "",
        "simplePast": "spread",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "spread",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 86,
        "infinitive": "to blow",
        "infinitiveExtraInfo": "",
        "simplePast": "blew",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "blown",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 87,
        "infinitive": "to burn",
        "infinitiveExtraInfo": "",
        "simplePast": "burned",
        "simplePastAlt": "burnt",
        "simplePastExtraInfo": "burned\" is more common in US English",
        "pastParticiple": "burned",
        "pastParticipleAlt": "burnt",
        "pastParticipleExtraInfo": "burned\" is more common in US English",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 88,
        "infinitive": "to shut",
        "infinitiveExtraInfo": "",
        "simplePast": "shut",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "shut",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 89,
        "infinitive": "to bear",
        "infinitiveExtraInfo": "in the sense of \"birth",
        "simplePast": "bore",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "born",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 90,
        "infinitive": "to bear",
        "infinitiveExtraInfo": "in the sense of \"carry, tolerate",
        "simplePast": "bore",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "borne",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 91,
        "infinitive": "to wake",
        "infinitiveExtraInfo": "",
        "simplePast": "woke",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "woken",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 92,
        "infinitive": "to steal",
        "infinitiveExtraInfo": "",
        "simplePast": "stole",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "stolen",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 93,
        "infinitive": "to cast",
        "infinitiveExtraInfo": "",
        "simplePast": "cast",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "cast",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 94,
        "infinitive": "to slide",
        "infinitiveExtraInfo": "",
        "simplePast": "slid",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "slid",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 95,
        "infinitive": "to bend",
        "infinitiveExtraInfo": "",
        "simplePast": "bent",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "bent",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 96,
        "infinitive": "to tear",
        "infinitiveExtraInfo": "",
        "simplePast": "tore",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "torn",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 97,
        "infinitive": "to ring",
        "infinitiveExtraInfo": "",
        "simplePast": "rang",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "rung",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": false
    },
    {
        "popularityRank": 98,
        "infinitive": "to light",
        "infinitiveExtraInfo": "",
        "simplePast": "lit",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "lit",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 99,
        "infinitive": "to swing",
        "infinitiveExtraInfo": "",
        "simplePast": "swung",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "swung",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 100,
        "infinitive": "to dig",
        "infinitiveExtraInfo": "",
        "simplePast": "dug",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "dug",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    },
    {
        "popularityRank": 101,
        "infinitive": "to grind",
        "infinitiveExtraInfo": "",
        "simplePast": "ground",
        "simplePastAlt": "",
        "simplePastExtraInfo": "",
        "pastParticiple": "ground",
        "pastParticipleAlt": "",
        "pastParticipleExtraInfo": "",
        "pastFormsEqual": true
    }
];